// Favor não bisbilhotar o código!
// 
// 

const information = {
  MTTH3S: {
    nome: "Tetheu",
    fotoCard: ["https://pbs.twimg.com/media/GCSyoxIWEAAJYyE?format=jpg&name=4096x4096", "https://pbs.twimg.com/media/GCUQ042WcAAwjOT?format=jpg&name=4096x4096",  'https://pbs.twimg.com/media/GCS0K3dWQAAsQgx?format=jpg&name=large','https://pbs.twimg.com/media/GCSyp2tW0AAotPy?format=jpg&name=4096x4096', 'https://pbs.twimg.com/media/GCS0LDpWoAAGJO5?format=jpg&name=large', 'https://pbs.twimg.com/media/GCXUkrMXQAAhdFU?format=jpg&name=large'],
    nomeCard: ["Opostos", "Mudança",  'Cativar',"Admiração", 'Acontecimentos', 'Obrigado'],
    textoCard: [
      'Oii Theus, quanto tempoooo kkkkkkk, estamos chegando ao fim de vários ciclos e recentemente eu me peguei pensando “Por que nós somos tão amigos se nós somos tão diferentes um do outro?”, tipo é só ver seus outros amigos, eles são esquizo engualzinho você tlgd, daí eu tava pensando, tipo somos extremamente diferentes, mas, ao mesmo tempo estranhamente iguais e eu acho que é justamente isso que nos une, nós nos complementamos, pois, cada um meio que adiciona um pouco no outro, um lado extrovertido, outro introvertido, um tímido, outro mais solto, um mais racional (nem sempre) e outro mais emotivo (até demais as vezes hein pqpkkk). Pensei muito mesmo sobre isso esses dias e percebi que por mais que a gente viva falando que somos parecidos e etc, a realidade é que somos diferentes p krlh também, mas mesmo assim continuamos juntos, pois tal como os ímãs os “opostos se atraem” kkkkkkk papo d viado da prr. Mas enfim, fico muito feliz pelo modo no qual ambos ajudamos um ao outro a evoluir como pessoa.',
      'Bom, eu queria muito te falar que tá tudo bem as coisas mudarem e que a mudança é normal e que temos que aceitar ela da melhor forma possível, mas infelizmente eu estaria mentindo se não dissesse que também tenho medo da mudança, morro de medo, mas eu me engano, prefiro viver uma mentira de que eu não tenho medo ou não me importo, pois <strong>“Às vezes, a verdade é um segredo que você está escondendo de si mesmo porque viver uma mentira é mais fácil”</strong>. Infelizmente, por mais que não goste de admitir, eu me importo pra krlh, eu falo que tô feliz que acabei a escola e que não sinto tanta falta, mas a real é que falta algo em mim desde que ela acabou. Sobre a gente, gosto p krlh de como as coisas estão e tenho muito medo da mudança em qualquer cosia a respeito, tenho medo da distância, tenho medo de acordar algum dia e não ter aquela mensagem de um retardado com jeito de viado surtando no meu privado ou falando merda dizendo que tá cagando a cada dois segundos kkkkkkk. A real é que quando você sumiu porque precisava de um tempo, eu tratei como se fosse algo normal no início, fosse ficar bem de boa com a semana afastado e até falei cm você como se não me importasse tanto, mas depois que você se foi, eu percebi que eu me importo p krlh e tenho medo d muita coisa, é aquilo né, a gente só sabe a falta que faz quando perde etckkkk. Enfim, a verdade é que eu me engano demais, estaria sendo hipócrita p krlh se te falasse que tá tudo bem na mudança, você é tipo o Finn do meu Jake, tlgd?',
      'O que tenho para te dizer é que, cara, você realmente me cativou tlgd, com seu jeito desajeitado um tanto quanto estranho e suas aleatoriedades. De início eu só tinha me aproximado de você pra poder ajudar o haru e saber mais sobre, mas porraaaa, aos poucos comecei a achar seu jeito muito foda e engraçado sla, só sei que depois do dia do aniversário, quando você criou a priv, acho que aí sim comecei a me aproximar mais, eu meio que acabei invadindo sua privacidade e com isso vendo seus desabafoskkkkkk com o tempo isso acabou deixando a gnt mais próximo, mas acho que a gnt realmente virou amigo dps do negócio que teve do haru que ele começou a ficar com o Dudu, talvez vc tenha ficado mais próximo, pois estava sem ninguém para falar com, mas isso acabou nos aproximando de certa forma, enfim até então eu (acho) que você confiava em mim, mas para ser sincero eu não confiava tanto em você, tipo pra desabafar e coisa do tipo sabe? Mas enfim, quando notei você já era a pessoa em que eu mais confiavakkkkk. Sério mesmo seu jeito me cativou de verdade, você é uma pessoa incrível cara, seu jeito meio alegre e maluco me faz sentir bem juro, posso até mesmo estar num lugar que não gosto ou sla, mas se você for sei que será legal, você faz até a coisa mais desinteressante se tornar legal com suas “resenhas”. Você definitivamente é uma pessoa especial, por quem se vale a pena lutar, nunca pensei que aquele moleke estranho dos sonhos iria virar alguém tão especial para mim. Olha, eu não sei se a gente vai continuar próximo assim, mas se eventualmente a distância chegar, saiba que você sempre vai ser aquela boa memória cujo eu olho pra trás, lembro e penso "Nossa, realmente foi um tempo tão bom, como krlhs será que aquele maluco tá hoje?", com certeza eu levarei muito de você para minha vida, mesmo que não estejamos juntos, de certa forma sempre vou te levar junto comigo, pois me cativastes, assim como a raposa disse <strong>“você é eternamente responsável por aquilo que cativas”</strong>, sempre estarei levando uma parte de você comigo seja lá onde eu estiver.',
      'Cara, a real é que eu sempre te admirei p krlh, você pode até achar que não, mas várias características suas são incríveis e dignas de reconhecimento, sempre te admirei muito pela sua coragem de se mostrar e o modo como você não tem medo dos julgamentos alheios até porque, eles não importam??? Seu jeito extrovertido de socializar rápido também sempre me surpreendeu, entre outras coisas. Além de tudo isso você também se importa bastante com as pessoas, é bom ver como você sempre está lá, você dava o seu máximo só pra ver um simples sorriso e nunca mediu esforços para deixar alguém que gosta feliz. Sei que para você devem ser coisas bestas, mas são coisas que definitivamente eu não consigo fazer e por isso eu sempre te admirei p krlh e pra ser sincero eu até já quis ser como você kkkkk. Fico muito feliz que você finalmente está começando a reconhecer o valor que tem e ter mais autoestima, pois poxa me doía como você se via mds, era uma maneira totalmente distorcida, fico orgulhoso por você estar evoluindo dessa forma e tão rápido kkkkkk. Eu sempre te admirei tanto que hoje carrego comigo vários de seus jeitos, sempre que eu fizer algo que sei que peguei de você, vou me lembrar da pessoa que você era e por consequência sentir saudades de tudo.',
      'Sei que todos os acontecimentos desse ano foram muito impactantes na sua vida e no momento você está tentando se recuperar de um deles, também sei que nada do que eu fale vai te fazer se sentir melhor ou coisa do tipo, imagino que você esteja cansado de tudo isso, me desculpa por ficar voltando nisso às vezes ok? Juro que não é por mal, eu percebo que às vezes nitidamente você não quer falar sobre aquilo, mas mesmo assim continuei o assunto algumas vezes, peço desculpas por qualquer coisa e juro que cada ação minha foi genuinamente pensando no seu bem, falei igual a uma mãe agrkkk. Sei que o esperado seria eu falar a respeito dos acontecimentos agora, mas não tô afim, imagino que ainda vai rolar muita coisa e talvez muita merda futuramente, por isso eu só gostaria de te pedir algumas coisas, fale tudo para Gabi por favor, ela sabe o que faz, conte de uma maneira realista e nunca romantizada, escute seus amigos também, às vezes a gnt fala merda, mas como estamos fora da situação conseguimos ver melhor o que realmente está acontecendo, por último gostaria de pedir para você pensar mais antes de agir, muito das merdas que você fez foi por isso, agir por impulso, mas infelizmente isso não dá muito certo em boa parte das vezes, não trate isso como sermão ou sla, é somente um conselho que te dou caso algo aconteça, sabe? Nunca se sabe. Enfim, por mais merda que tenha sido, fico feliz que os acontecimentos tenham acabado nos unindo, além disso, peço desculpas por qualquer coisa que já tenha feito e te deixado mal ou sla.',
      'Para finalizar, eu gostaria de esclarecer que eu amaria ter feito uma carta, mas infelizmente não sou tão bom com essas coisas, por isso fiz com algo que tenho habilidade, pode até n ser tanta coisa assim, mas saiba que foi feito com muito carinho, inclusive não sei se percebeu mas estou finalizando essa carta com a nossa primeira foto. Enfim, antes que este ano termine, eu só quero agradecer por hoje poder te chamar de melhor amigo, o amigo mais incrível que eu poderia pedir. Obrigado por ouvir meus desabafos, surtos aleatórios e até mesmo talvez fingir que se importa com algo que claramente você não liga kkkkkk. Obrigado por sempre estar lá para mim quando eu precisava de alguém para conversar ou só de um ombro amigo para me apoiar e me ouvir.  Acredito que nada vai poder expressar o quão sortudo e grato eu sou por ter um amigo foda como você. Quero que você lembre eu vou estar aqui sempre que precisar de um ombro para se apoiar, alguém para desabafar ou até mesmo alguém para ouvir as piadas mais merdas e ofensivas possíveis kkkkk, mesmo que a vida nos separe você sempre será uma memória boa. Pprt cara eu amo você, Feliz ano novo e eu espero que seu 2024 seja tão incrível quanto a pessoa que você é. <br><br> <iframe style="border-radius:20px background-color: hsla(10, 40%, 40%, 1);" src="https://open.spotify.com/embed/track/21uFPefbgeR3QLVJWATlrr?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'],
    cor: ['22', '184',  '220','200', '200', '10']
  },
  TRR3S: {
    nome: "Julinha",
    fotoCard: ["https://pbs.twimg.com/media/GCUNuKtWsAAVl6H?format=jpg&name=4096x4096", "https://pbs.twimg.com/media/GCUNtzUXYAAThIf?format=jpg&name=large", 'https://pbs.twimg.com/media/GCUPCUFXQAAn3rr?format=jpg&name=large', 'https://pbs.twimg.com/media/GCUPCIwXEAATNUE?format=jpg&name=large'],
    nomeCard: ["Companhia", "Momentos", 'Sempre', 'Obrigado'],
    textoCard: ["Olá Julinha, primeiramente eu só queria te agradecer por todo esse tempo junto, tipo, a gente se conhece faz quase 4 anos kkkk e mds me sinto muito mal por não ter me aproximado de você antes, namoral, você é uma pessoa incrível demais, seu jeito alegre, tagalera e meio atrapalhado às vezes me encanta, seu sorriso ilumina onde não há luz, já tiveram vezes em que eu estava triste naquela viagem de “sc” e só de falar com você meu brilho já voltava, sua alegria é contagiante pqp, além de tudo você é uma pessoa muito gentil, sério mesmo, fiquei muito feliz naquela primeira vez que você me chamou a sua casa no dia da família, eu real não tava esperando, fiquei muito feliz de verdade mesmo que em alguns momentos a gente tenha ficado meio sem saber o que fazer já que não éramos tão próximos kkkk, mas mesmo assim você me chamou, deu para ver que você tinha muita consideração por mim, isso me deixou genuinamente feliz. É incrível ver como todos os meus amigos que te conheceram, gostaram muito de você logo de cara, você é uma pessoa excepcional e além de tudo muito dedicada e inteligente, admiro muito isso em você.",
     "É muito louco pensar que só viramos amigos por conta da pandemia, às vezes eu me pego pensando como teria sido se ela não tivesse acontecido, tipo teria evitado muita desgraça, mas porra, eu gosto de como tudo aconteceu, posso estar sendo egoísta por isso, mas só pelo fato disso ter feito nós nos conhecermos já faz valer a pena. Namoral, sou extremamente grato por cada momento que eu já passei com você, todas as memórias que tenho junto a você são genuinamente felizes só pelo fato de você estar lá, todas às vezes em que o clima pesava por alguma coisa e você tentava o deixar mais leve, todas as sextas culturais ou trotes nitidamente flopados, mas você fazia eles serem legais, você trazia luz, chamando todo mundo para dançar com você, mesmo sem saber dançar todas essas memórias são incríveis, as sextas culturais e trotes nunca mais foram os mesmos desde que você se foi, com isso percebi que não era o trote que era legal, mas sim o fato de poder ter sua companhia naquele lugar, como, por exemplo, todos os dias em que ficávamos passeando pelo refeitório enquanto desabafávamos sobre a vida, aquilo só foi bom graças a você, depois que você viajou os intervalos do prédio novo não tinham mais graça. De verdade foi muito incrível viajar com você, eu adoraria ter ficado no mesmo hotel só para gente poder fazer uma festinha do pijama, pedindo pizza e assistindo algum filme ou slakkkk, tenho muitas saudades daquela viagem, principalmente por estar realizando um sonho junto de você, cada momento foi extremamente especial, foi muito bom a reciprocidade de apoio entre nós dois com nossas desilusões amorosas kkkkk, sério mesmo, é ótimo perceber que passei os melhores momentos do meu ano junto a você, sou muito agradecido por isso, pois vejo que sem você eles não seriam o mesmo, você me faz muito feliz Julinha, sua amizade é um motivo de felicidade. ",
      'Eu só queria te falar que estou muito orgulhoso por tudo que você está conquistando agora e genuinamente feliz por isso, é ótimo ver uma pessoa que amo tanto vencendo e conquistando as coisas que quer, gostaria de falar que apesar da distância, estarei sempre te apoiando, sempre torcendo por você, sabe aquela pulseira que você me deu no São joão? Nunca tirei ela, pretendo continuar com ela por muito tempo para sempre que eu notar que ela está em meu braço, lembrar de você e consequentemente ficar feliz por saber que você está feliz, o mesmo vale para a pulseira que fizemos em outubro de 2021, não estou em 100% do tempo com ela mas sempre que saio a coloco para te levar junto comigo, quero continuar vivendo meus melhores momentos junto a você mesmo que seja somente de forma significativa com um presente que me deu, ela me lembra de tudo que vivemos e por isso ganhou muito significado para mim. Nós dois vamos para caminhos bem diferentes em nossa vida, quero que você saiba que eu sempre estarei torcendo por você, ok? Mesmo que o acaso venha nos separar, sempre vou estar. Sei que tá sendo difícil para você se adaptar com todo esse mundo novo de independência, mas sei que você vai se acostumar e consequentemente conseguir tudo o que quer.',
       'Para finalizar, antes eu só gostaria de agradecer por todo esse tempo em que ficamos juntos, espero que seu ano de 2024 seja cheio de vitórias e seja um ano tão incrível quanto a pessoa que você é, você merece muito. Só gostaria de dizer que eu te amo muito, muito mesmo de verdade, espero que você esteja feliz aí onde você está. Gostaria de falar também que sinto muitas saudades de você, gostaria muito de estar te acompanhando nessa sua nova etapa da vida, mas infelizmente como isso não é possível fico aqui torcendo do meu cantinho kkkk. Eu só quero que você seja feliz, estarei sempre torcendo por isso. Quero que você lembre, eu estarei aqui sempre que precisar de um ombro para se apoiar, alguém para desabafar ou sla só para ouvir as emoções de um provável amor kkkkk, mesmo que a vida nos separe você sempre será uma boa memória no qual lembro e penso, valeu a pena p krlh. Enfim foi issokkkk te amo demais viu, obrigado de verdade.'],
    cor: ['210', '20', '12', '40']
  },
  RYH0SE: {
    nome: "Olhinhos",
    fotoCard: ["https://pbs.twimg.com/media/GCUHx17XAAAEFB7?format=jpg&name=medium", "https://pbs.twimg.com/media/GCUIG4VX0AAFCgl?format=png&name=small", 'https://pbs.twimg.com/media/GCUHeMUX0AAqhm_?format=png&name=small'],
    nomeCard: ["Sorriso", "Irys", 'Card'],
    textoCard: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque maximus volutpat lorem vitae auctor. Nam quam erat, faucibus ac justo non, dignissim luctus velit. Proin convallis nibh sit amet nibh porta interdum. Quisque pharetra aliquet luctus. Sed ac euismod dolor, et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.", "texto2", 'algo'],
    cor: ['20', '352', '30']
  },
  C4RLTS: {
    nome: "Carlinhos",
    fotoCard: ["https://pbs.twimg.com/media/GCUWMB8WsAAqQZj?format=jpg&name=large", 'https://pbs.twimg.com/media/GCUWL3SWIAAFgmX?format=jpg&name=large', 'https://pbs.twimg.com/media/GCUYMTtWoAA-odv?format=jpg&name=small'],
    nomeCard: ["Carlitos", "tt", 'Card'],
    textoCard: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque maximus volutpat lorem vitae auctor. Nam quam erat, faucibus ac justo non, dignissim luctus velit. Proin convallis nibh sit amet nibh porta interdum. Quisque pharetra aliquet luctus. Sed ac euismod dolor, et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.", "texto2", 'algo'],
    cor: ['200', '30', '250']
  },
};
