// Favor não bisbilhotar o código!
// 
// 

const information = {
  MTTH3S: {
    nome: "Tetheu",
    fotoCard: ["https://pbs.twimg.com/media/GCSyoxIWEAAJYyE?format=jpg&name=4096x4096", "https://pbs.twimg.com/media/GCUQ042WcAAwjOT?format=jpg&name=4096x4096",  'https://pbs.twimg.com/media/GCS0K3dWQAAsQgx?format=jpg&name=large','https://pbs.twimg.com/media/GCSyp2tW0AAotPy?format=jpg&name=4096x4096', 'https://pbs.twimg.com/media/GCS0LDpWoAAGJO5?format=jpg&name=large', 'https://pbs.twimg.com/media/GCXUkrMXQAAhdFU?format=jpg&name=large'],
    nomeCard: ["Opostos", "Mudança",  'Cativar',"Admiração", 'Acontecimentos', 'Obrigado'],
    textoCard: [
      'Oii Theus, quanto tempoooo kkkkkkk, estamos chegando ao fim de vários ciclos e recentemente eu me peguei pensando “Por que nós somos tão amigos se nós somos tão diferentes um do outro?”, tipo é só ver seus outros amigos, eles são esquizo engualzinho você tlgd, daí eu tava pensando, tipo somos extremamente diferentes, mas, ao mesmo tempo estranhamente iguais e eu acho que é justamente isso que nos une, nós nos complementamos, pois, cada um meio que adiciona um pouco no outro, um lado extrovertido, outro introvertido, um tímido, outro mais solto, um mais racional (nem sempre) e outro mais emotivo (até demais as vezes hein pqpkkk). Pensei muito mesmo sobre isso esses dias e percebi que por mais que a gente viva falando que somos parecidos e etc, a realidade é que somos diferentes p krlh também, mas mesmo assim continuamos juntos, pois tal como os ímãs os “opostos se atraem” kkkkkkk papo d viado da prr. Mas enfim, fico muito feliz pelo modo no qual ambos ajudamos um ao outro a evoluir como pessoa.',
      'Bom, eu queria muito te falar que tá tudo bem as coisas mudarem e que a mudança é normal e que temos que aceitar ela da melhor forma possível, mas infelizmente eu estaria mentindo se não dissesse que também tenho medo da mudança, morro de medo, mas eu me engano, prefiro viver uma mentira de que eu não tenho medo ou não me importo, pois <strong>“Às vezes, a verdade é um segredo que você está escondendo de si mesmo porque viver uma mentira é mais fácil”</strong>. Infelizmente, por mais que não goste de admitir, eu me importo pra krlh, eu falo que tô feliz que acabei a escola e que não sinto tanta falta, mas a real é que falta algo em mim desde que ela acabou. Sobre a gente, gosto p krlh de como as coisas estão e tenho muito medo da mudança em qualquer cosia a respeito, tenho medo da distância, tenho medo de acordar algum dia e não ter aquela mensagem de um retardado com jeito de viado surtando no meu privado ou falando merda dizendo que tá cagando a cada dois segundos kkkkkkk. A real é que quando você sumiu porque precisava de um tempo, eu tratei como se fosse algo normal no início, fosse ficar bem de boa com a semana afastado e até falei cm você como se não me importasse tanto, mas depois que você se foi, eu percebi que eu me importo p krlh e tenho medo d muita coisa, é aquilo né, a gente só sabe a falta que faz quando perde etckkkk. Enfim, a verdade é que eu me engano demais, estaria sendo hipócrita p krlh se te falasse que tá tudo bem na mudança, você é tipo o Finn do meu Jake, tlgd?',
      'O que tenho para te dizer é que, cara, você realmente me cativou tlgd, com seu jeito desajeitado um tanto quanto estranho e suas aleatoriedades. De início eu só tinha me aproximado de você pra poder ajudar o haru e saber mais sobre, mas porraaaa, aos poucos comecei a achar seu jeito muito foda e engraçado sla, só sei que depois do dia do aniversário, quando você criou a priv, acho que aí sim comecei a me aproximar mais, eu meio que acabei invadindo sua privacidade e com isso vendo seus desabafoskkkkkk com o tempo isso acabou deixando a gnt mais próximo, mas acho que a gnt realmente virou amigo dps do negócio que teve do haru que ele começou a ficar com o Dudu, talvez vc tenha ficado mais próximo, pois estava sem ninguém para falar com, mas isso acabou nos aproximando de certa forma, enfim até então eu (acho) que você confiava em mim, mas para ser sincero eu não confiava tanto em você, tipo pra desabafar e coisa do tipo sabe? Mas enfim, quando notei você já era a pessoa em que eu mais confiavakkkkk. Sério mesmo seu jeito me cativou de verdade, você é uma pessoa incrível cara, seu jeito meio alegre e maluco me faz sentir bem juro, posso até mesmo estar num lugar que não gosto ou sla, mas se você for sei que será legal, você faz até a coisa mais desinteressante se tornar legal com suas “resenhas”. Você definitivamente é uma pessoa especial, por quem se vale a pena lutar, nunca pensei que aquele moleke estranho dos sonhos iria virar alguém tão especial para mim. Olha, eu não sei se a gente vai continuar próximo assim, mas se eventualmente a distância chegar, saiba que você sempre vai ser aquela boa memória cujo eu olho pra trás, lembro e penso "Nossa, realmente foi um tempo tão bom, como krlhs será que aquele maluco tá hoje?", com certeza eu levarei muito de você para minha vida, mesmo que não estejamos juntos, de certa forma sempre vou te levar junto comigo, pois me cativastes, assim como a raposa disse <strong>“você é eternamente responsável por aquilo que cativas”</strong>, sempre estarei levando uma parte de você comigo seja lá onde eu estiver.',
      'Cara, a real é que eu sempre te admirei p krlh, você pode até achar que não, mas várias características suas são incríveis e dignas de reconhecimento, sempre te admirei muito pela sua coragem de se mostrar e o modo como você não tem medo dos julgamentos alheios até porque, eles não importam??? Seu jeito extrovertido de socializar rápido também sempre me surpreendeu, entre outras coisas. Além de tudo isso você também se importa bastante com as pessoas, é bom ver como você sempre está lá, você dava o seu máximo só pra ver um simples sorriso e nunca mediu esforços para deixar alguém que gosta feliz. Sei que para você devem ser coisas bestas, mas são coisas que definitivamente eu não consigo fazer e por isso eu sempre te admirei p krlh e pra ser sincero eu até já quis ser como você kkkkk. Fico muito feliz que você finalmente está começando a reconhecer o valor que tem e ter mais autoestima, pois poxa me doía como você se via mds, era uma maneira totalmente distorcida, fico orgulhoso por você estar evoluindo dessa forma e tão rápido kkkkkk. Eu sempre te admirei tanto que hoje carrego comigo vários de seus jeitos, sempre que eu fizer algo que sei que peguei de você, vou me lembrar da pessoa que você era e por consequência sentir saudades de tudo.',
      'Sei que todos os acontecimentos desse ano foram muito impactantes na sua vida e no momento você está tentando se recuperar de um deles, também sei que nada do que eu fale vai te fazer se sentir melhor ou coisa do tipo, imagino que você esteja cansado de tudo isso, me desculpa por ficar voltando nisso às vezes ok? Juro que não é por mal, eu percebo que às vezes nitidamente você não quer falar sobre aquilo, mas mesmo assim continuei o assunto algumas vezes, peço desculpas por qualquer coisa e juro que cada ação minha foi genuinamente pensando no seu bem, falei igual a uma mãe agrkkk. Sei que o esperado seria eu falar a respeito dos acontecimentos agora, mas não tô afim, imagino que ainda vai rolar muita coisa e talvez muita merda futuramente, por isso eu só gostaria de te pedir algumas coisas, fale tudo para Gabi por favor, ela sabe o que faz, conte de uma maneira realista e nunca romantizada, escute seus amigos também, às vezes a gnt fala merda, mas como estamos fora da situação conseguimos ver melhor o que realmente está acontecendo, por último gostaria de pedir para você pensar mais antes de agir, muito das merdas que você fez foi por isso, agir por impulso, mas infelizmente isso não dá muito certo em boa parte das vezes, não trate isso como sermão ou sla, é somente um conselho que te dou caso algo aconteça, sabe? Nunca se sabe. Enfim, por mais merda que tenha sido, fico feliz que os acontecimentos tenham acabado nos unindo, além disso, peço desculpas por qualquer coisa que já tenha feito e te deixado mal ou sla.',
      'Para finalizar, eu gostaria de esclarecer que eu amaria ter feito uma carta, mas infelizmente não sou tão bom com essas coisas, por isso fiz com algo que tenho habilidade, pode até n ser tanta coisa assim, mas saiba que foi feito com muito carinho. Enfim, antes que este ano termine, eu só quero agradecer por hoje poder te chamar de melhor amigo, o amigo mais incrível que eu poderia pedir. Obrigado por ouvir meus desabafos, surtos aleatórios e até mesmo talvez fingir que se importa com algo que claramente você não liga kkkkkk. Obrigado por sempre estar lá para mim quando eu precisava de alguém para conversar ou só de um ombro amigo para me apoiar e me ouvir.  Acredito que nada vai poder expressar o quão sortudo e grato eu sou por ter um amigo foda como você. Quero que você lembre eu vou estar aqui sempre que precisar de um ombro para se apoiar, alguém para desabafar ou até mesmo alguém para ouvir as piadas mais merdas e ofensivas possíveis kkkkk, mesmo que a vida nos separe você sempre será uma memória boa. Pprt cara eu amo você, Feliz ano novo e eu espero que seu 2024 seja tão incrível quanto a pessoa que você é. <br><br> <iframe style="border-radius:20px background-color: hsla(10, 40%, 40%, 1);" src="https://open.spotify.com/embed/track/21uFPefbgeR3QLVJWATlrr?utm_source=generator" width="100%" height="152" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>'],
    cor: ['22', '184',  '220','200', '200', '10']
  },
  TRR3S: {
    nome: "Julinha",
    fotoCard: ["https://pbs.twimg.com/media/GCUNuKtWsAAVl6H?format=jpg&name=4096x4096", "https://pbs.twimg.com/media/GCUNtzUXYAAThIf?format=jpg&name=large", 'https://pbs.twimg.com/media/GCUPCUFXQAAn3rr?format=jpg&name=large', 'https://pbs.twimg.com/media/GCUPCIwXEAATNUE?format=jpg&name=large'],
    nomeCard: ["Lorem Ipsum", "nome2", 'título 3', 't4'],
    textoCard: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque maximus volutpat lorem vitae auctor. Nam quam erat, faucibus ac justo non, dignissim luctus velit. Proin convallis nibh sit amet nibh porta interdum. Quisque pharetra aliquet luctus. Sed ac euismod dolor, et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.", "texto2", '00', '00'],
    cor: ['210', '20', '12', '40']
  },
  RYH0SE: {
    nome: "Olhinhos",
    fotoCard: ["https://pbs.twimg.com/media/GCUHx17XAAAEFB7?format=jpg&name=medium", "https://pbs.twimg.com/media/GCUIG4VX0AAFCgl?format=png&name=small", 'https://pbs.twimg.com/media/GCUHeMUX0AAqhm_?format=png&name=small'],
    nomeCard: ["Sorriso", "Irys", 'Card'],
    textoCard: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque maximus volutpat lorem vitae auctor. Nam quam erat, faucibus ac justo non, dignissim luctus velit. Proin convallis nibh sit amet nibh porta interdum. Quisque pharetra aliquet luctus. Sed ac euismod dolor, et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.", "texto2", 'algo'],
    cor: ['20', '352', '30']
  },
  C4RLTS: {
    nome: "Carlinhos",
    fotoCard: ["https://pbs.twimg.com/media/GCUWMB8WsAAqQZj?format=jpg&name=large", 'https://pbs.twimg.com/media/GCUWL3SWIAAFgmX?format=jpg&name=large', 'https://pbs.twimg.com/media/GCUYMTtWoAA-odv?format=jpg&name=small'],
    nomeCard: ["Carlitos", "tt", 'Card'],
    textoCard: ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque maximus volutpat lorem vitae auctor. Nam quam erat, faucibus ac justo non, dignissim luctus velit. Proin convallis nibh sit amet nibh porta interdum. Quisque pharetra aliquet luctus. Sed ac euismod dolor, et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.et rutrum mi. Maecenas consectetur, quam sed pellentesque varius, diam tellus dictum diam, quis tristique libero urna at magna. Etiam mattis auctor libero eu posuere.", "texto2", 'algo'],
    cor: ['200', '30', '250']
  },
};